First commit since Creators update

diff --git a/logrotate.d/mysql-server b/logrotate.d/mysql-server
--- a/logrotate.d/mysql-server
+++ b/logrotate.d/mysql-server
@@ -1,8 +1,8 @@
-# - I put everything in one block and added sharedscripts, so that mysql gets 
+# - I put everything in one block and added sharedscripts, so that mysql gets
 #   flush-logs'd only once.
 #   Else the binary logs would automatically increase by n times every day.
 # - The error log is obsolete, messages go to syslog now.
-/var/log/mysql.log /var/log/mysql/mysql.log /var/log/mysql/mariadb-slow.log {
+/var/log/mysql.log /var/log/mysql/mysql.log /var/log/mysql/mysql-slow.log /var/log/mysql/mariadb-slow.log /var/log/mysql/error.log {
 	daily
 	rotate 7
 	missingok
@@ -10,11 +10,18 @@
 	compress
 	sharedscripts
 	postrotate
-          test -x /usr/bin/mysqladmin || exit 0
+		test -x /usr/bin/mysqladmin || exit 0
 
-          if [ -f `my_print_defaults --mysqld | grep -oP "pid-file=\K[^$]+"` ]; then
-            # If this fails, check debian.conf!
-            mysqladmin --defaults-file=/etc/mysql/debian.cnf flush-logs
-          fi
+		# If this fails, check debian.conf!
+		MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
+		if [ -z "`$MYADMIN ping 2>/dev/null`" ]; then
+		  # Really no mysqld or rather a missing debian-sys-maint user?
+		  # If this occurs and is not a error please report a bug.
+		  if ps cax | grep -q mysqld; then
+ 		    exit 1
+		  fi
+		else
+		  $MYADMIN flush-logs
+		fi
 	endscript
 }
